import type { Metadata } from "next";
import { unstable_setRequestLocale } from 'next-intl/server'
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, modal
}: {
  children: React.ReactNode;
  modal: React.ReactNode
}) {

    unstable_setRequestLocale('en')
  return (
    <html lang="en">
      <body className={inter.className}>
      {children}

      <br/>
      <br/>
      {modal}
      </body>
    </html>
  );
}
