import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../globals.css";

const inter = Inter({subsets: ["latin"]});
const locales = ['en', 'de', 'fr', 'it', 'nl', 'es', 'pt', 'pl']


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const dynamicParams = false

//Needed for static rendering
//Docs on https://next-intl-docs.vercel.app/docs/getting-started/app-router#static-rendering
export function generateStaticParams() {
    return locales.map(locale => ({locale}))
}

export default function RootLayout({
                                       children, modal
                                   }: {
    children: React.ReactNode;
    modal: React.ReactNode
}) {

    return (
        <html lang="en">
        <body className={inter.className}>
        {children}

        <br/>
        <br/>
        {modal}
        </body>
        </html>
    );
}
